"use client"

import { useEffect } from "react"
import Aos from "aos"
import Image from "next/image"

import History from "@/assets/history.png"
import TokenFeature from "@/assets/token.png"
import Toob from "@/assets/toob.png"

const Token = () => {
  useEffect(() => {
    Aos.init({
      duration: 600,
      offset: 100,
      once: true,
    })
  }, [])

  return (
    <div className="relative overflow-hidden flex justify-center pt-24 lg:pt-32 pb-7 lg:pb-14">
      <div className="container px-5 md:px-10 lg:px-[100px] xl:px-[150px] 3xl:px-0 flex justify-between items-center relative z-[1]">
        <div className="lg:w-1/2 lg:flex flex-col lg:justify-center max-lg:hidden">
          <Image
            src={History.src}
            data-aos="fade-right"
            width={History.width}
            height={History.height}
            alt="history"
            priority
            className="w-[120px] md:w-[200px] lg:w-full lg:max-w-[500px]"
          />
          <Image
            src={TokenFeature.src}
            data-aos="fade-right"
            width={TokenFeature.width}
            height={TokenFeature.height}
            alt="token"
            priority
            className="w-[120px] md:w-[200px] lg:w-full lg:max-w-[500px]"
          />
        </div>
        <div className="lg:w-1/2 ml-5 xl:ml-20">
          <Image
            src={History.src}
            data-aos="fade-right"
            width={History.width}
            height={History.height}
            alt="history"
            priority
            className="w-[150px] sm:w-[200px] md:w-[300px] float-left lg:hidden"
          />
          <h3
            data-aos="fade-down"
            className="flex items-center justify-end sm:text-xl md:text-3xl font-bold"
          >
            <Image
              src={Toob.src}
              width={Toob.width}
              height={Toob.height}
              alt="toob"
              className="w-16 mr-3 max-lg:hidden"
            />
            Token & History
          </h3>
          <p
            data-aos="fade-left"
            className="text-xs md:text-xl font-medium mt-6 lg:mt-9"
          >
            Toob Finance introduces its own token, TOOB, operating on the
            Arbitrum Network. Initially launched as a memecoin with a fair
            launch, TOOB sets itself apart with a commitment to decentralization
            – no VCs, no sale or pre-sale, and no contract ownership.
            Furthermore, liquidity is 100% burned, ensuring transparency and
            trust within the community.
            <br />
            <Image
              src={TokenFeature.src}
              data-aos="fade-right"
              width={TokenFeature.width}
              height={TokenFeature.height}
              alt="token"
              priority
              className="w-full max-w-[400px] mx-auto lg:hidden"
            />
            <br />
            As we progressed, we recognized the challenge of onboarding
            non-crypto users to the Toob ecosystem, as they needed to grasp the
            intricacies of DeFi before participating fully. This realization led
            to the development of a Fiat to Toob gateway, paving the way for the
            inception of Toob Finance. Acknowledging that many developers and
            projects faced the same hurdle, we sought to create a universal
            solution to streamline accessibility with free and easy access for
            all.
            <br />
            <br />
            The TOOB token serves as the backbone of Toob Finance, with revenues
            generated by the venture reinvested into the Toob ecosystem, driving
            growth and sustainability. Through TOOB, we empower users and
            developers alike, fostering a community-driven approach to
            decentralized finance.
          </p>
        </div>
      </div>
    </div>
  )
}

export default Token
